version: '3.8'
services:
  rp-service:
    build: 
      context: ./
      dockerfile: Dockerfile
    image: rp-docker-image
    container_name: rp-docker-container
    restart: unless-stopped
    working_dir: /home/gta/server/
    privileged: true
    ports:
      - "40120:40120"
      - "30120:30120"
      - "30120:30120/udp"
      - "40120:40120/udp"
    env_file:
      - .env
    volumes:
      - ./:/home/gta/server
    networks:
      - gta-network

  db:
    image: mariadb:11.3.2
    command: --default-authentication-plugin=mysql_native_password && bash -c "mysqld --user=root --max_connections=5000"
    container_name: rp-db-container
    restart: unless-stopped
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - gta-network

networks:
  gta-network:
    driver: bridge